---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zookeeper-n2
  namespace: {{.NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-n2
  template:
    metadata:
      labels:
        app: zookeeper-n2
    spec:
      hostname: zookeeper-n2
      volumes:
        - name: zookeeper-data
          hostPath:
            path: /data/zookeeper-cluster/zookeeper-data-n2
        - name: zookeeper-logs
          hostPath:
            path: /data/zookeeper-cluster/zookeeper-logs-n2
      dnsPolicy: ClusterFirst
      containers:
        - name: zookeeper-n2
          image: zookeeper:3.4.10
          imagePullPolicy: Always
          volumeMounts:
            - name: zookeeper-data
              readOnly: false
              mountPath: "/data/zookeeper-data"
            - name: zookeeper-logs
              readOnly: false
              mountPath: "/data/zookeeper-logs"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          #command: ['tail', '-f', '/etc/hosts']
          env:
            - name: ZOO_MY_ID
              value: "2"
            - name: ZOO_SERVERS
              value: server.1=zookeeper-n1:2888:3888 server.2=zookeeper-n2:2888:3888 server.3=zookeeper-n3:2888:3888
            - name: ZOO_DATA_DIR
              value: '/data/zookeeper-data'
            - name: ZOO_DATA_LOG_DIR
              value: '/data/zookeeper-logs'
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-n2
  name: zookeeper-n2
  namespace: default
spec:
  ports:
    - port: 2181
      protocol: TCP
      targetPort: 2181
      name: client
    - port: 2888
      protocol: TCP
      targetPort: 2888
      name: leader
    - port: 3888
      protocol: TCP
      targetPort: 3888
      name: leader-election
  selector:
    app: zookeeper-n2
  sessionAffinity: None
  type: ClusterIP